import { BiLogoVisualStudio } from "react-icons/bi";
import { DiVisualstudio } from "react-icons/di";
import { FaJava } from "react-icons/fa6";
import {
  SiAuth0,
  SiCss3,
  SiDocker,
  SiDotnet,
  SiEslint,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiGit,
  SiGithub,
  SiGnubash,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiJsonwebtokens,
  SiLinux,
  SiMongodb,
  SiNetlify,
  SiNodedotjs,
  SiPostman,
  SiPython,
  SiReact,
  SiReactquery,
  SiReactrouter,
  SiSpringboot,
  SiSwagger,
  SiTypescript,
  SiVite,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";

export const TechstackList: TechstackListProps[] = [
  {
    key: "frontend",
    label: "Front-end",
    list: [
      { key: "react", label: "React", icon: <SiReact /> },
      { key: "eslint", label: "ESLint", icon: <SiEslint /> },
      { key: "reactquery", label: "React-Query", icon: <SiReactquery /> },
      { key: "reactrouter", label: "React-Router", icon: <SiReactrouter /> },
      { key: "jest", label: "Jest", icon: <SiJest /> },
      { key: "vite", label: "Vite", icon: <SiVite /> },
      { key: "typescript", label: "TypeScript", icon: <SiTypescript /> },
      { key: "javascript", label: "JavaScript", icon: <SiJavascript /> },
      { key: "css", label: "CSS", icon: <SiCss3 /> },
      { key: "html", label: "HTML", icon: <SiHtml5 /> },
    ],
  },
  {
    key: "backend",
    label: "Back-end",
    list: [
      { key: "expressjs", label: "Express.js", icon: <SiExpress /> },
      { key: "springboot", label: "Springboot", icon: <SiSpringboot /> },
      { key: "aspdotnetcore", label: "ASP.NET Core", icon: <SiDotnet /> },
      { key: "fastapi", label: "FastAPI", icon: <SiFastapi /> },
      { key: "nodejs", label: "Node.js", icon: <SiNodedotjs /> },
      { key: "java", label: "Java", icon: <FaJava /> },
      { key: "csharp", label: "C#", icon: <TbBrandCSharp /> },
      { key: "python", label: "Python", icon: <SiPython /> },
      { key: "jwt", label: "JWT", icon: <SiJsonwebtokens /> },
      { key: "auth0", label: "Auth0", icon: <SiAuth0 /> },
      { key: "mongodb", label: "MongoDB", icon: <SiMongodb /> },
    ],
  },
  {
    key: "devtools",
    label: "Dev Tools",
    list: [
      { key: "gnulinux", label: "GNU/Linux", icon: <SiLinux /> },
      { key: "docker", label: "Docker", icon: <SiDocker /> },
      { key: "postman", label: "Postman", icon: <SiPostman /> },
      { key: "bash", label: "Bash", icon: <SiGnubash /> },
      { key: "git", label: "Git", icon: <SiGit /> },
      { key: "github", label: "GitHub", icon: <SiGithub /> },
      { key: "swagger", label: "Swagger", icon: <SiSwagger /> },
      { key: "netlify", label: "Netlify", icon: <SiNetlify /> },
      { key: "vscode", label: "VSCode", icon: <BiLogoVisualStudio /> },
      { key: "visualstudio", label: "Visual Studio", icon: <DiVisualstudio /> },
      { key: "figma", label: "Figma", icon: <SiFigma /> },
    ],
  },
];
